CSHARP=mcs
MAIN_CLASS= main.cs
PARTIAL_CLASSES= Learjet.cs Location.cs Passenger.cs FlightPlanner.cs Airport.cs Runway.cs graph.cs 


all:
	$(CSHARP) $(OPT) $(MAIN_CLASS) $(PARTIAL_CLASSES)

clean:
	rm *.exe
